version: '3.8'

# 🚀 Auto Aziz - Configuration Docker Développement
services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: autoaziz-postgres-dev
    environment:
      POSTGRES_DB: autoaziz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - autoaziz-network

  # Redis pour le cache (optionnel)
  redis:
    image: redis:7-alpine
    container_name: autoaziz-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - autoaziz-network

  # Backend NestJS (développement)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: autoaziz-backend-dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=autoaziz
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - autoaziz-network
    restart: unless-stopped

  # Frontend React (développement)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: autoaziz-frontend-dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - autoaziz-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  autoaziz-network:
    driver: bridge
    name: autoaziz-network
